version: '3.7'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # 추가 설정, es 접속시 보안 설정 (id, password) 무시
      - xpack.security.authc.api_key.enabled=false
      - xpack.security.authc.token.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200 # https
      - 9300:9300 # tcp
    networks:
      - es-bridge

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - XPACK_SECURITY_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=d1a4b8f2c3e6m7n9p0q5r8t2u4v6w8x7y3z9
      # Security Solution 관련 설정 추가
      - XPACK_SECURITY_SECURITYSOLUTION_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_AUDIT_ENABLED=false
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - es-bridge
    restart: always

volumes:
  mysql-data: # mysql 볼륨 정의
    driver: local

  es-data: # Elasticsearch 볼륨 정의
    driver: local

networks:
  es-bridge:
    driver: bridge