spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

logging:
  config: classpath:logback-spring.xml


